# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-24 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0006_i18n'),
        ('indigo_api', '0053_work_view_perm'),
        ('indigo_app', '0009_publication'),
        ('indigo_workflow', '0002_reviewworkprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePointInTimeProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('date', models.DateField(help_text=b'Date of the point in time to create')),
                ('approved', models.BooleanField(default=False)),
                ('amendment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_pit_tasks', to='indigo_api.Amendment')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indigo_app.Language')),
                ('work', models.ForeignKey(help_text=b'Work to create point in time for', on_delete=django.db.models.deletion.CASCADE, related_name='create_pit_tasks', to='indigo_api.Work')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
