# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 08:34
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('place_code', models.CharField(db_index=True, max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=20, null=True)),
                ('n_works', models.IntegerField()),
                ('n_expressions', models.IntegerField(null=True)),
                ('n_points_in_time', models.IntegerField(null=True)),
                ('n_expected_expressions', models.IntegerField(null=True)),
                ('n_complete_works', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'indigo_metrics_daily_workmetrics',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyworkmetrics',
            unique_together=set([('date', 'place_code')]),
        ),
    ]
