# Generated by Django 3.2.13 on 2022-06-24 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0014_remove_tags'),
        ('indigo_metrics', '0001_squashed_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_bytes', models.IntegerField(default=0)),
                ('n_provisions', models.IntegerField(default=0)),
                ('n_words', models.IntegerField(default=0)),
                ('n_pages', models.IntegerField(default=0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='indigo_api.document')),
            ],
        ),
    ]
