# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_metrics', '0003_auto_20190510_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkmetrics',
            name='p_breadth_complete',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailyworkmetrics',
            name='p_complete',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailyworkmetrics',
            name='p_depth_complete',
            field=models.IntegerField(null=True),
        ),
    ]
