# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 07:11
from __future__ import unicode_literals

from django.db import migrations, connection


def backfill_completeness(apps, schema_editor):
    # Backfill p_depth_complete and p_complete on daily metrics.
    # We don't have enough information to backfill p_breadth_complete.
    db_alias = schema_editor.connection.alias
    with connection(using=db_alias).cursor() as cursor:
        cursor.execute("""
UPDATE
  indigo_metrics_daily_workmetrics
SET
  p_depth_complete = CASE WHEN n_expected_expressions = 0 THEN 100 ELSE (100::float * n_expressions / n_expected_expressions)::int END,
  p_complete       = CASE WHEN n_expected_expressions = 0 THEN 100 ELSE (100::float * n_expressions / n_expected_expressions)::int END
WHERE
  p_depth_complete IS NULL
  AND p_complete IS NULL 
""")


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_metrics', '0004_auto_20190511_0643'),
    ]

    operations = [
        migrations.RunPython(backfill_completeness, migrations.RunPython.noop)
    ]
