# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-01 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_metrics', '0005_backfill_completeness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmetrics',
            name='n_expected_expressions',
            field=models.IntegerField(help_text='Expected number of published documents', null=True),
        ),
        migrations.AlterField(
            model_name='workmetrics',
            name='n_expressions',
            field=models.IntegerField(help_text='Number of published documents', null=True),
        ),
        migrations.AlterField(
            model_name='workmetrics',
            name='n_languages',
            field=models.IntegerField(help_text='Number of languages in published documents', null=True),
        ),
        migrations.AlterField(
            model_name='workmetrics',
            name='n_points_in_time',
            field=models.IntegerField(help_text='Number of recorded points in time', null=True),
        ),
        migrations.AlterField(
            model_name='workmetrics',
            name='p_breadth_complete',
            field=models.IntegerField(help_text='Percentage breadth complete', null=True),
        ),
        migrations.AlterField(
            model_name='workmetrics',
            name='p_complete',
            field=models.IntegerField(help_text='Percentage complete', null=True),
        ),
        migrations.AlterField(
            model_name='workmetrics',
            name='p_depth_complete',
            field=models.IntegerField(help_text='Percentage depth complete', null=True),
        ),
    ]
