[build-system]
requires = ["setuptools", "setuptools_scm[toml]>=6.2", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["docs"]

[project]
name = "indigo"
description = "A Django application for publishing legislation using Akoma Ntoso"
readme = "README.md"
requires-python = ">= 3.10"
authors = [
    {name = "Laws.Africa", email = "info@laws.africa"}
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Django :: 4.2",
    "Intended Audience :: Legal Industry",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "django>=4.2,<5",
    "boto3>=1.7",
    "urllib3<2.1",  # botocore doesn"t play well with urllib3 > 2.1 see https://github.com/boto/botocore/issues/2926
    "bluebell-akn>=3.1.0",
    "cssutils>=2.3.0",
    "django-ckeditor>=5.8",
    "dj-database-url>=0.3.0",
    "django-activity-stream>=0.10.0",
    "django-allauth[socialaccount]>=64.0.0",
    "django-background-tasks-updated>=1.2.8",
    "django-compressor>=3.1,<=4.4",
    "django-cors-headers>=3.11.0",
    "django-countries-plus>=2.0.1",
    "django-filter>=24.3",
    "django-fsm>=2.6.0",
    "django-htmx>=1.15.0",
    "django-languages-plus>=1.1.1",
    "django-pipeline>=1.6.11,<3.1.0",
    "django-recaptcha>=4.0.0",
    "django-reversion>=3.0.9",
    "django-sass-processor>=1.1",
    "django-sass-processor-dart-sass>=0.0.1",
    "django-storages>=1.12.3",
    "django-templated-email>=2.3.0",
    "django-treebeard>=4.5.1",
    "djangorestframework-xml>=1.3.0",
    "djangorestframework>=3.15.0",
    "docpipe @ git+https://github.com/laws-africa/docpipe@5ceee068e0bb2929e33f080c2d1f3063eff0857d",
    "drf-spectacular==0.28.0",
    "EbookLib>=0.15",
    "google-api-python-client>=1.7.9",
    "iso8601>=0.1",
    "jsonpatch>=1.23",
    "lxml>=5.0.0",
    "mammoth>=1.4.4",
    "natsort>=8.3",
    "requests>=2",
    "unicodecsv>=0.14.1",
    "whitenoise==5.3.0",
    "django-contrib-comments>=1.9.1",
    "XlsxWriter>=1.2.6",
    # unreleased version of xmldiff that allows us to ignore attributes when diffing
    "xmldiff @ git+https://github.com/Shoobx/xmldiff@6980256b10ffa41b5ab80716e63a608f587126db#egg=xmldiff",
    "sentry-sdk>=1.16.0",

    # for indigo_social
    "pillow>=5.2.0",
]
dynamic = ["version"]

[project.urls]
"Homepage" = "https://github.com/laws-africa/indigo"
"Bug Tracker" = "https://github.com/laws-africa/indigo/issues"

[project.optional-dependencies]
dev = [
    "nose",
    "flake8",
    "django-nose>=1.4.4",
]
test = [
    "nose",
    "flake8",
    "django-nose>=1.4.4",
    "coveralls",
    "django-webtest>=1.9.4",
    "dotmap>=1.3.8",
    "sheet2dict==0.1.5"
]
docs = [
    "psycopg2-binary",
]

[tool.setuptools.dynamic]
version = {attr = "indigo.version.__version__"}
