# Generated by Django 2.2.12 on 2020-10-29 14:29

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import indigo_api.models.documents
import taggit.managers


class Migration(migrations.Migration):

    replaces = [('indigo_api', '0001_initial'), ('indigo_api', '0002_auto_20150114_0639'), ('indigo_api', '0003_auto_20150114_1549'), ('indigo_api', '0004_auto_20150204_0948'), ('indigo_api', '0005_auto_20150204_1035'), ('indigo_api', '0006_auto_20150216_1027'), ('indigo_api', '0007_document_deleted'), ('indigo_api', '0008_auto_20150217_0905'), ('indigo_api', '0009_auto_20150308_1645'), ('indigo_api', '0010_auto_20150505_1315'), ('indigo_api', '0011_auto_20150505_1356'), ('indigo_api', '0012_document_assent_date'), ('indigo_api', '0013_document_stub'), ('indigo_api', '0014_auto_20150505_1444'), ('indigo_api', '0015_auto_20150520_1455'), ('indigo_api', '0016_subtype_tweak'), ('indigo_api', '0017_tweak_language_field'), ('indigo_api', '0018_delete_subtype'), ('indigo_api', '0019_tweak_country'), ('indigo_api', '0020_subtype'), ('indigo_api', '0021_document_expression_date'), ('indigo_api', '0022_attachment'), ('indigo_api', '0023_auto_20150614_1338'), ('indigo_api', '0024_auto_20150918_1515'), ('indigo_api', '0025_auto_20150921_1025'), ('indigo_api', '0026_colophon'), ('indigo_api', '0027_auto_20160220_2005'), ('indigo_api', '0028_random_uris_20170208_0523'), ('indigo_api', '0029_help_text'), ('indigo_api', '0030_annotation'), ('indigo_api', '0031_activity'), ('indigo_api', '0032_search'), ('indigo_api', '0033_publication_details'), ('indigo_api', '0034_repeal'), ('indigo_api', '0035_amendments'), ('indigo_api', '0036_work'), ('indigo_api', '0037_document_work'), ('indigo_api', '0038_auto_20180324_1116'), ('indigo_api', '0039_remove_work_draft'), ('indigo_api', '0040_remove_doc_assent_comm'), ('indigo_api', '0041_work_repeal'), ('indigo_api', '0042_add_repeal_works'), ('indigo_api', '0043_doc_repeal_event'), ('indigo_api', '0044_work_parent_work'), ('indigo_api', '0045_amendment'), ('indigo_api', '0046_works_for_amendments'), ('indigo_api', '0047_remove_document_amendment_events'), ('indigo_api', '0048_work_commencing_work'), ('indigo_api', '0049_remove_deleted_works'), ('indigo_api', '0050_hard_delete_works'), ('indigo_api', '0051_publication_date_is_date'), ('indigo_api', '0052_review_work_perm'), ('indigo_api', '0053_work_view_perm'), ('indigo_api', '0054_view_published_doc_perms'), ('indigo_api', '0055_document_expression_dates'), ('indigo_api', '0056_doc_requires_expression_date'), ('indigo_api', '0057_blanks'), ('indigo_api', '0058_import_language_country_from_indigo_app')]

    initial = True

    dependencies = [
        ('languages_plus', '0002_auto_20141008_0947'),
        ('taggit', '0001_initial'),
        ('countries_plus', '0002_auto_20150120_2225'),
        ('countries_plus', '0005_auto_20160224_1804'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frbr_uri', models.CharField(help_text='Used globally to identify this work', max_length=512, unique=True)),
                ('title', models.CharField(default=b'(untitled)', max_length=1024, null=True)),
                ('country', models.CharField(default=b'za', max_length=2)),
                ('publication_name', models.CharField(blank=True, help_text='Original publication, eg. government gazette', max_length=255, null=True)),
                ('publication_number', models.CharField(blank=True, help_text="Publication's sequence number, eg. gazette number", max_length=255, null=True)),
                ('publication_date', models.DateField(blank=True, help_text=b'Date of publication', null=True)),
                ('commencement_date', models.DateField(blank=True, help_text='Date of commencement unless otherwise specified', null=True)),
                ('assent_date', models.DateField(blank=True, help_text='Date signed by the president', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('repealed_by', models.ForeignKey(blank=True, help_text=b'Work that repealed this work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repealed_works', to='indigo_api.Work')),
                ('repealed_date', models.DateField(blank=True, help_text=b'Date of repeal of this work', null=True)),
                ('parent_work', models.ForeignKey(blank=True, help_text=b'Parent related work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_works', to='indigo_api.Work')),
                ('commencing_work', models.ForeignKey(blank=True, help_text=b'Date that marked this work as commenced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commenced_works', to='indigo_api.Work')),
            ],
            options={
                'permissions': (('review_work', 'Can review work details'), ('view_work', 'Can list and view work details')),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frbr_uri', models.CharField(default=b'/', help_text=b'Used globally to identify this work', max_length=512)),
                ('title', models.CharField(max_length=1024)),
                ('draft', models.BooleanField(default=True, help_text=b"Drafts aren't available through the public API")),
                ('document_xml', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(default=b'za', max_length=2)),
                ('deleted', models.BooleanField(default=False, help_text=b'Has this document been deleted?')),
                ('language', models.CharField(default=b'eng', max_length=3)),
                ('stub', models.BooleanField(default=False, help_text=b'Is this a placeholder document without full content?')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('expression_date', models.DateField(help_text=b'Date of publication or latest amendment')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('search_text', models.TextField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigo_api.Work')),
            ],
            options={
                'permissions': (('publish_document', 'Can publish and edit non-draft documents'), ('view_published_document', 'Can view publish documents through the API')),
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('anchor_id', models.CharField(max_length=512)),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='indigo_api.Document')),
                ('in_reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indigo_api.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='indigo_api.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document', 'user', 'nonce')},
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=indigo_api.models.documents.attachment_filename)),
                ('size', models.IntegerField()),
                ('filename', models.CharField(db_index=True, help_text=b'Unique attachment filename', max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='indigo_api.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Colophon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Name of this colophon', max_length=1024)),
                ('body', models.TextField()),
                ('country', models.ForeignKey(blank=True, help_text=b'Which country does this colophon apply to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries_plus.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text=b'Date of the amendment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amended_work', models.ForeignKey(help_text=b'Work amended.', on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='indigo_api.Work')),
                ('amending_work', models.ForeignKey(help_text=b'Work making the amendment.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indigo_api.Work')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Name of the document subtype', max_length=1024)),
                ('abbreviation', models.CharField(help_text=b'Short abbreviation to use in FRBR URI. No punctuation.', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Document subtype',
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Country',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='countries_plus.Country')),
                    ],
                    options={
                        'ordering': ['country__name'],
                        'verbose_name_plural': 'Countries',
                    },
                ),
                migrations.CreateModel(
                    name='Language',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='languages_plus.Language')),
                    ],
                    options={
                        'ordering': ['language__name_en'],
                    },
                ),
                migrations.AddField(
                    model_name='country',
                    name='primary_language',
                    field=models.ForeignKey(help_text=b'Primary language for this country', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='indigo_api.Language'),
                ),
            ],
        ),
    ]
