# Generated by Django 2.2.12 on 2020-11-19 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0001_squashed_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='indigo_api.Country'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
