# Generated by Django 2.2.12 on 2021-01-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0002_alter_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomyvocabulary',
            options={'ordering': ('title',), 'verbose_name': 'Taxonomy', 'verbose_name_plural': 'Taxonomies'},
        ),
        migrations.AlterModelOptions(
            name='vocabularytopic',
            options={'ordering': ('level_1', 'level_2')},
        ),
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='authority',
            field=models.CharField(help_text='Organisation managing this taxonomy', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='name',
            field=models.CharField(help_text='Short name for this taxonomy, under this authority', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='title',
            field=models.CharField(help_text='Friendly, full title for the taxonomy', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='vocabularytopic',
            name='level_1',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='vocabularytopic',
            name='level_2',
            field=models.CharField(blank=True, help_text='(optional)', max_length=512, null=True),
        ),
    ]
