# Generated by Django 2.2.12 on 2021-01-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0003_alter_taxonomies'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesettings',
            name='no_publication_document_text',
            field=models.CharField(blank=True, default='Note: The original publication document is not available and this content could not be verified.', max_length=1024),
        ),
    ]
