# Generated by Django 2.2.12 on 2021-07-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0006_commencement_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='as_at_date',
            field=models.DateField(blank=True, help_text='Date up to which this work was last checked for updates', null=True),
        ),
    ]
