# Generated by Django 2.2.12 on 2021-09-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0007_work_as_at_date_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='authority',
            field=models.CharField(help_text='Organisation managing this taxonomy', max_length=512),
        ),
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='name',
            field=models.CharField(help_text='Short name for this taxonomy, under this authority', max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='taxonomyvocabulary',
            unique_together={('authority', 'name')},
        ),
    ]
