# Generated by Django 2.2.20 on 2021-10-29 11:35

from django.db import migrations
from indigo_api.data_migrations import RealCrossHeadings


def forwards(apps, schema_editor):
    from indigo_api.models import Document
    from indigo_api.models import Annotation

    db_alias = schema_editor.connection.alias
    migration = RealCrossHeadings()

    for doc in Document.objects.using(db_alias):
        if migration.migrate_document(doc):
            doc.save()

            # update annotations
            for old, new in migration.eid_mappings.items():
                Annotation.objects.using(db_alias)\
                    .filter(document_id=doc.id, anchor_id=old)\
                    .update(anchor_id=new)


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0009_migrate_attachment_eids'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
