# Generated by Django 2.2.12 on 2022-01-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0011_language_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesettings',
            name='consolidation_note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='consolidation_note_override',
            field=models.CharField(blank=True, help_text='Consolidation note about this particular work, to override consolidation note for place', max_length=1024, null=True),
        ),
    ]
