# Generated by Django 3.2.15 on 2022-09-23 17:35

from django.db import migrations

from cobalt import FrbrUri


def forwards(apps, schema_editor):
    """ Migrate attachment eIds.
    """
    Work = apps.get_model('indigo_api', 'Work')
    db_alias = schema_editor.connection.alias

    for work in Work.objects.using(db_alias).iterator(100):
        print(f"Migrating {work.frbr_uri}")
        work_uri = FrbrUri.parse(work.frbr_uri)

        # extract FRBR URI fields
        work.doctype = work_uri.doctype
        work.subtype = work_uri.subtype
        work.actor = work_uri.actor
        work.date = work_uri.date
        work.number = work_uri.number
        work.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0015_work_frbr_fields'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
