# Generated by Django 3.2.15 on 2022-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0016_migrate_work_frbr_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.CharField(help_text='FRBR date', max_length=10, blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='doctype',
            field=models.CharField(help_text='FRBR doctype', max_length=64, blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='number',
            field=models.CharField(help_text='FRBR number', max_length=512, blank=True),
        ),
    ]
