# Generated by Django 3.2.12 on 2022-11-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0017_work_frbr_fields_non_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='principal',
            field=models.BooleanField(default=False, help_text='Principal works are not simply repeals, amendments or commencements, and should have full text content.'),
        ),
    ]
