# Generated by Django 3.2.12 on 2022-11-03 09:26
import logging

from django.db import migrations


log = logging.getLogger(__name__)


def backfill_principal_works(apps, schema_editor):
    """ Mark existing works as principal works if the works:
    - have at least one document associated with them; OR
    - works that do not repeal, amend or commence another work
    """
    Work = apps.get_model('indigo_api', 'Work')
    db_alias = schema_editor.connection.alias

    for work in Work.objects.using(db_alias).iterator(100):
        if work.document_set.exists() or (not work.commencements_made.exists() and
                not work.repealed_works.exists() and not work.amendments_made.exists()):
            log.info(f'\nMarking {work.frbr_uri} as a principal work...')
            work.principal = True
            work.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0018_principal_work'),
    ]

    operations = [
        migrations.RunPython(backfill_principal_works, migrations.RunPython.noop)
    ]
