# Generated by Django 3.2.15 on 2022-11-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0019_backfill_principal_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='publication_date_optional',
            field=models.BooleanField(default=False, help_text='Are publication dates optional in this country?'),
        ),
    ]
