# Generated by Django 3.2.13 on 2023-01-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0020_country_publication_date_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='disclaimer',
            field=models.CharField(blank=True, help_text='Disclaimer text about this work', max_length=1024, null=True),
        ),
    ]
