# Generated by Django 3.2.18 on 2023-02-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0021_work_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesettings',
            name='is_consolidation',
            field=models.BooleanField(default=False, help_text='Is a consolidation being worked on in this country?'),
        ),
        migrations.AddField(
            model_name='placesettings',
            name='uses_chapter',
            field=models.BooleanField(default=False, help_text='Are Chapters used for Acts in this country?'),
        ),
    ]
