# Generated by Django 3.2.18 on 2023-02-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0022_place_settings_is_consolidation_uses_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesettings',
            name='publication_date_optional',
            field=models.BooleanField(default=False, help_text='Are publication dates optional in this place?'),
        ),
    ]
