# Generated by Django 3.2.18 on 2023-02-28 13:44
import logging

from django.db import migrations


log = logging.getLogger(__name__)


def forward(apps, schema_editor):
    """ Mark place settings as publication_date_optional if the relevant country is marked as such.
    """
    Country = apps.get_model('indigo_api', 'Country')
    PlaceSettings = apps.get_model('indigo_api', 'PlaceSettings')
    db_alias = schema_editor.connection.alias

    for country in Country.objects.using(db_alias).filter(publication_date_optional=True):
        log.info(f"\nMarking {country.country.name}'s place settings as publication_date_optional = True ...")
        place_settings = PlaceSettings.objects.using(db_alias).get(country=country)
        place_settings.publication_date_optional = True
        place_settings.save()


def backward(apps, schema_editor):
    """ Mark countries as publication_date_optional if the relevant place settings is marked as such.
    """
    PlaceSettings = apps.get_model('indigo_api', 'PlaceSettings')
    db_alias = schema_editor.connection.alias

    for place_settings in PlaceSettings.objects.using(db_alias).filter(publication_date_optional=True):
        country = place_settings.country
        log.info(f"\nMarking {country.country.name} as publication_date_optional = True ...")
        country.publication_date_optional = True
        country.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0023_placesettings_publication_date_optional'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
