# Generated by Django 3.2.18 on 2023-02-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0024_move_publication_date_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='publication_date_optional',
        ),
    ]
