# Generated by Django 3.2.13 on 2023-10-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0026_taxonomy_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomytopic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
