# Generated by Django 3.2.13 on 2023-11-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0027_taxonomytopic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments about this work', null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='draft',
            field=models.BooleanField(default=False, help_text='Is this a draft work?'),
        ),
    ]
