# Generated by Django 3.2.15 on 2023-11-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0027_taxonomytopic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomytopic',
            name='slug',
            field=models.SlugField(max_length=4096, unique=True),
        ),
    ]
