# Generated by Django 3.2.13 on 2023-12-06 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indigo_api', '0028_alter_taxonomytopic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='approved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='work',
            name='approved_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='work',
            name='work_in_progress',
            field=models.BooleanField(default=False, help_text='Work in progress, to be approved'),
        ),
    ]
