# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0028_random_uris_20170208_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='stub',
            field=models.BooleanField(default=False, help_text=b'Is this a placeholder document without full content?'),
        ),
    ]
