# Generated by Django 3.2.13 on 2024-01-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0030_backfill_work_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeline_date',
            field=models.DateField(blank=True, help_text='A date on the timeline of work-related tasks, e.g. the date at which an amendment should be applied.', null=True),
        ),
    ]
