# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 14:24
from django.db import migrations, models
from cobalt import Act


def set_publication_details(apps, schema_editor):
    Document = apps.get_model("indigo_api", "Document")
    db_alias = schema_editor.connection.alias
    for doc in Document.objects.using(db_alias).all():
        a = Act(doc.document_xml)
        doc.publication_number = a.publication_number
        doc.publication_name = a.publication_name
        doc.publication_date = a.publication_date
        doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0032_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='publication_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='publication_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='publication_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            set_publication_details,
            migrations.RunPython.noop,
            elidable=True)
    ]
