# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 15:02
import django.contrib.postgres.fields.jsonb
from django.db import migrations
from cobalt import Act, datestring


def set_repeal_details(apps, schema_editor):
    Document = apps.get_model("indigo_api", "Document")
    db_alias = schema_editor.connection.alias
    for doc in Document.objects.using(db_alias).all():
        a = Act(doc.document_xml)
        repeal = a.repeal
        if repeal:
            doc.repeal_event = {
                'date': datestring(repeal.date),
                'repealing_title': repeal.repealing_title,
                'repealing_uri': repeal.repealing_uri,
            }
            doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0033_publication_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='repeal_event',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.RunPython(
            set_repeal_details,
            migrations.RunPython.noop,)
    ]
