# Generated by Django 3.2.13 on 2024-03-06 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indigo_api', '0034_taskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
