# Generated by Django 3.2.15 on 2024-03-07 15:22

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import indigo_api.models.documents
import indigo_api.models.tasks
import indigo_api.models.works


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages_plus', '0004_auto_20171214_0004'),
        ('countries_plus', '0005_auto_20160224_1804'),
        ('indigo_api', '0035_task_finished_by_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amendment',
            options={'ordering': ['date'], 'verbose_name': 'amendment', 'verbose_name_plural': 'amendments'},
        ),
        migrations.AlterModelOptions(
            name='annotation',
            options={'verbose_name': 'annotation', 'verbose_name_plural': 'annotations'},
        ),
        migrations.AlterModelOptions(
            name='arbitraryexpressiondate',
            options={'ordering': ['date'], 'verbose_name': 'arbitrary expression date', 'verbose_name_plural': 'arbitrary expression dates'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ('filename',), 'verbose_name': 'attachment', 'verbose_name_plural': 'attachments'},
        ),
        migrations.AlterModelOptions(
            name='colophon',
            options={'verbose_name': 'colophon', 'verbose_name_plural': 'colophons'},
        ),
        migrations.AlterModelOptions(
            name='commencement',
            options={'ordering': ['date'], 'verbose_name': 'commencement', 'verbose_name_plural': 'commencements'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country__name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('publish_document', 'Can publish and edit non-draft documents'), ('view_published_document', 'Can view publish documents through the API'), ('view_document_xml', 'Can view the source XML of documents')), 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
        migrations.AlterModelOptions(
            name='documentactivity',
            options={'ordering': ('created_at',), 'verbose_name': 'document activity', 'verbose_name_plural': 'document activities'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'base_manager_name': 'objects', 'ordering': ['language__name_en'], 'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ['name'], 'verbose_name': 'locality', 'verbose_name_plural': 'localities'},
        ),
        migrations.AlterModelOptions(
            name='placesettings',
            options={'verbose_name': 'place settings', 'verbose_name_plural': "places' settings"},
        ),
        migrations.AlterModelOptions(
            name='publicationdocument',
            options={'verbose_name': 'publication document', 'verbose_name_plural': 'publication documents'},
        ),
        migrations.AlterModelOptions(
            name='subtype',
            options={'ordering': ('name',), 'verbose_name': 'subtype', 'verbose_name_plural': 'subtypes'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('submit_task', 'Can submit an open task for review'), ('cancel_task', 'Can cancel a task that is open or has been submitted for review'), ('reopen_task', 'Can reopen a task that is closed or cancelled'), ('unsubmit_task', 'Can unsubmit a task that has been submitted for review'), ('close_task', 'Can close a task that has been submitted for review'), ('close_any_task', 'Can close any task that has been submitted for review, regardless of who submitted it'), ('block_task', 'Can block a task from being done, and unblock it'), ('exceed_task_limits', 'Can be assigned tasks in excess of limits')), 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskfile',
            options={'verbose_name': 'task file', 'verbose_name_plural': 'task files'},
        ),
        migrations.AlterModelOptions(
            name='tasklabel',
            options={'ordering': ['title'], 'verbose_name': 'task label', 'verbose_name_plural': 'task labels'},
        ),
        migrations.AlterModelOptions(
            name='taxonomyvocabulary',
            options={'ordering': ('title',), 'verbose_name': 'taxonomy', 'verbose_name_plural': 'taxonomies'},
        ),
        migrations.AlterModelOptions(
            name='vocabularytopic',
            options={'ordering': ('level_1', 'level_2'), 'verbose_name': 'vocabulary topic', 'verbose_name_plural': 'vocabulary topics'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'permissions': (('review_work', 'Can review work details'), ('bulk_add_work', 'Can import works in bulk'), ('bulk_export_work', 'Can export works in bulk')), 'verbose_name': 'work', 'verbose_name_plural': 'works'},
        ),
        migrations.AlterModelOptions(
            name='workalias',
            options={'ordering': ('alias',), 'verbose_name': 'work alias', 'verbose_name_plural': 'work aliases'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ('-priority', 'pk'), 'permissions': (('close_workflow', 'Can close a workflow'),), 'verbose_name': 'workflow', 'verbose_name_plural': 'workflows'},
        ),
        migrations.AlterField(
            model_name='amendment',
            name='amended_work',
            field=models.ForeignKey(help_text='Work being amended', on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='indigo_api.work', verbose_name='amended work'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='amending_work',
            field=models.ForeignKey(help_text='Work making the amendment', on_delete=django.db.models.deletion.CASCADE, related_name='amendments_made', to='indigo_api.work', verbose_name='amending work'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='date',
            field=models.DateField(help_text='Date on which the amendment comes into operation', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='updated_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='anchor_id',
            field=models.CharField(max_length=512, verbose_name='anchor id'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='closed'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='indigo_api.document', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='in_reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indigo_api.annotation', verbose_name='in reply to'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='selectors',
            field=models.JSONField(null=True, verbose_name='selectors'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation', to='indigo_api.task', verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='arbitraryexpressiondate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='arbitraryexpressiondate',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='arbitraryexpressiondate',
            name='date',
            field=models.DateField(help_text='Arbitrary date, e.g. consolidation date', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='arbitraryexpressiondate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='arbitraryexpressiondate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='arbitraryexpressiondate',
            name='updated_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='arbitraryexpressiondate',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrary_expression_dates', to='indigo_api.work', verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='indigo_api.document', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=indigo_api.models.documents.attachment_filename, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(db_index=True, help_text='Unique attachment filename', max_length=255, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(max_length=255, verbose_name='mime type'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='size',
            field=models.IntegerField(verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='colophon',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='colophon',
            name='country',
            field=models.ForeignKey(help_text='Which country does this colophon apply to?', on_delete=django.db.models.deletion.CASCADE, to='indigo_api.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='colophon',
            name='name',
            field=models.CharField(help_text='Name of this colophon', max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='commencement',
            name='all_provisions',
            field=models.BooleanField(default=False, help_text='All provisions of this work commenced on this date', verbose_name='all provisions'),
        ),
        migrations.AlterField(
            model_name='commencement',
            name='commenced_work',
            field=models.ForeignKey(help_text='Principal work being commenced', on_delete=django.db.models.deletion.CASCADE, related_name='commencements', to='indigo_api.work', verbose_name='commenced work'),
        ),
        migrations.AlterField(
            model_name='commencement',
            name='commencing_work',
            field=models.ForeignKey(help_text='Work that provides the commencement date for the principal work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commencements_made', to='indigo_api.work', verbose_name='commencing work'),
        ),
        migrations.AlterField(
            model_name='commencement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='commencement',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='commencement',
            name='date',
            field=models.DateField(blank=True, help_text='Date of the commencement, or null if it is unknown', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='commencement',
            name='main',
            field=models.BooleanField(default=False, help_text='This commencement date is the date on which most of the provisions of the commenced work come into force', verbose_name='main'),
        ),
        migrations.AlterField(
            model_name='commencement',
            name='note',
            field=models.TextField(blank=True, help_text='Usually a reference to a provision of the commenced work or a commencing work, if there is a commencement but the date is open to interpretation', max_length=1024, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='commencement',
            name='provisions',
            field=models.JSONField(default=list, help_text='A list of the element ids of the provisions that come into force with this commencement', verbose_name='commenced provisions'),
        ),
        migrations.AlterField(
            model_name='commencement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='commencement',
            name='updated_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='countries_plus.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='italics_terms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024, verbose_name='italics terms'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='country',
            name='primary_language',
            field=models.ForeignKey(help_text='Primary language for this country', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='indigo_api.language', verbose_name='primary language'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='document',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Has this document been deleted?', verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_xml',
            field=models.TextField(blank=True, null=True, verbose_name='document XML'),
        ),
        migrations.AlterField(
            model_name='document',
            name='draft',
            field=models.BooleanField(default=True, help_text="Drafts aren't available through the public API", verbose_name='draft'),
        ),
        migrations.AlterField(
            model_name='document',
            name='expression_date',
            field=models.DateField(help_text='Date of publication or latest amendment', verbose_name='expression date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='frbr_uri',
            field=models.CharField(default='/', help_text='Used globally to identify this work', max_length=512, verbose_name='frbr uri'),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.ForeignKey(help_text='Language this document is in.', on_delete=django.db.models.deletion.PROTECT, to='indigo_api.language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='document',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigo_api.work', verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='indigo_api.document', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='nonce',
            field=models.CharField(max_length=10, verbose_name='nonce'),
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_activities', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='languages_plus.language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='code',
            field=models.CharField(help_text='Unique code of this locality (used in the FRBR URI)', max_length=100, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='indigo_api.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(help_text='Local name of this locality', max_length=512, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='placesettings',
            name='as_at_date',
            field=models.DateField(blank=True, null=True, verbose_name='as-at date'),
        ),
        migrations.AlterField(
            model_name='placesettings',
            name='consolidation_note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='consolidation note'),
        ),
        migrations.AlterField(
            model_name='placesettings',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_settings', to='indigo_api.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='placesettings',
            name='is_consolidation',
            field=models.BooleanField(default=False, help_text='Is a consolidation being worked on in this place?', verbose_name='a consolidation is being imported'),
        ),
        migrations.AlterField(
            model_name='placesettings',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_settings', to='indigo_api.locality', verbose_name='locality'),
        ),
        migrations.AlterField(
            model_name='placesettings',
            name='no_publication_document_text',
            field=models.CharField(blank=True, default='Note: The original publication document is not available and this content could not be verified.', max_length=1024, verbose_name="'No publication document' text"),
        ),
        migrations.AlterField(
            model_name='placesettings',
            name='publication_date_optional',
            field=models.BooleanField(default=False, help_text='Are publication dates optional in this place?', verbose_name='publication date is optional'),
        ),
        migrations.AlterField(
            model_name='placesettings',
            name='spreadsheet_url',
            field=models.URLField(blank=True, null=True, verbose_name='spreadsheet URL'),
        ),
        migrations.AlterField(
            model_name='placesettings',
            name='styleguide_url',
            field=models.URLField(blank=True, null=True, verbose_name='styleguide URL'),
        ),
        migrations.AlterField(
            model_name='placesettings',
            name='uses_chapter',
            field=models.BooleanField(default=False, help_text='Are Chapters used for Acts in this place?', verbose_name='chapters are used'),
        ),
        migrations.AlterField(
            model_name='publicationdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='publicationdocument',
            name='file',
            field=models.FileField(upload_to=indigo_api.models.works.publication_document_filename, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='publicationdocument',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='publicationdocument',
            name='mime_type',
            field=models.CharField(max_length=255, verbose_name='file MIME type'),
        ),
        migrations.AlterField(
            model_name='publicationdocument',
            name='size',
            field=models.IntegerField(null=True, verbose_name='file size'),
        ),
        migrations.AlterField(
            model_name='publicationdocument',
            name='trusted_url',
            field=models.URLField(blank=True, null=True, verbose_name='trusted URL'),
        ),
        migrations.AlterField(
            model_name='publicationdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='publicationdocument',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_document', to='indigo_api.work', verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='abbreviation',
            field=models.CharField(help_text='Short abbreviation to use in the FRBR URI. No punctuation.', max_length=20, unique=True, verbose_name='abbreviation'),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='name',
            field=models.CharField(help_text='Name of the subtype', max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='assigned to'),
        ),
        migrations.AlterField(
            model_name='task',
            name='blocked_by',
            field=models.ManyToManyField(help_text='Tasks blocking this task from being done.', related_name='blocking', to='indigo_api.Task', verbose_name='blocked by'),
        ),
        migrations.AlterField(
            model_name='task',
            name='changes_requested',
            field=models.BooleanField(default=False, help_text='Have changes been requested on this task?', verbose_name='changes requested'),
        ),
        migrations.AlterField(
            model_name='task',
            name='closed_at',
            field=models.DateTimeField(help_text='When the task was marked as done or cancelled.', null=True, verbose_name='closed at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='task',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='indigo_api.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='indigo_api.document', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='task',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='extra data'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_tasks', to=settings.AUTH_USER_MODEL, verbose_name='finished by user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='input_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_as_input', to='indigo_api.taskfile', verbose_name='input file'),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(related_name='tasks', to='indigo_api.TaskLabel', verbose_name='labels'),
        ),
        migrations.AlterField(
            model_name='task',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='indigo_api.locality', verbose_name='locality'),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_as_output', to='indigo_api.taskfile', verbose_name='output file'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewed_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=django_fsm.FSMField(default='open', max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='task',
            name='submitted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_tasks', to=settings.AUTH_USER_MODEL, verbose_name='submitted by user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeline_date',
            field=models.DateField(blank=True, help_text='A date on the timeline of work-related tasks, e.g. the date at which an amendment should be applied.', null=True, verbose_name='timeline date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='indigo_api.work', verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=indigo_api.models.tasks.task_file_filename, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='filename',
            field=models.CharField(max_length=1024, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='mime_type',
            field=models.CharField(max_length=1024, verbose_name='mimetype'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='size',
            field=models.IntegerField(null=True, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tasklabel',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='tasklabel',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='tasklabel',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='taxonomytopic',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='taxonomytopic',
            name='name',
            field=models.CharField(max_length=512, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='taxonomytopic',
            name='public',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
        migrations.AlterField(
            model_name='taxonomytopic',
            name='slug',
            field=models.SlugField(max_length=4096, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='authority',
            field=models.CharField(help_text='Organisation managing this taxonomy', max_length=512, verbose_name='authority'),
        ),
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='name',
            field=models.CharField(help_text='Short name for this taxonomy, under this authority', max_length=512, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='slug',
            field=models.SlugField(help_text='Code used in the API', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='title',
            field=models.CharField(help_text='Friendly, full title for the taxonomy', max_length=512, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='vocabularytopic',
            name='level_1',
            field=models.CharField(max_length=512, verbose_name='level 1'),
        ),
        migrations.AlterField(
            model_name='vocabularytopic',
            name='level_2',
            field=models.CharField(blank=True, help_text='(optional)', max_length=512, null=True, verbose_name='level 2'),
        ),
        migrations.AlterField(
            model_name='vocabularytopic',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='indigo_api.taxonomyvocabulary', verbose_name='vocabulary'),
        ),
        migrations.AlterField(
            model_name='work',
            name='actor',
            field=models.CharField(blank=True, help_text='FRBR actor', max_length=512, null=True, verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='work',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='approved at'),
        ),
        migrations.AlterField(
            model_name='work',
            name='approved_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AlterField(
            model_name='work',
            name='as_at_date_override',
            field=models.DateField(blank=True, help_text='Date up to which this work was last checked for updates', null=True, verbose_name='as-at date override'),
        ),
        migrations.AlterField(
            model_name='work',
            name='assent_date',
            field=models.DateField(blank=True, help_text='Date signed by the president', null=True, verbose_name='assent date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='commenced',
            field=models.BooleanField(default=False, help_text='Has this work commenced? (Date may be unknown)', verbose_name='commenced'),
        ),
        migrations.AlterField(
            model_name='work',
            name='consolidation_note_override',
            field=models.CharField(blank=True, help_text='Consolidation note about this particular work, to override any consolidation note for the place', max_length=1024, null=True, verbose_name='consolidation note override'),
        ),
        migrations.AlterField(
            model_name='work',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='indigo_api.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.CharField(blank=True, help_text='FRBR date', max_length=10, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='disclaimer',
            field=models.CharField(blank=True, help_text='Disclaimer text about this work', max_length=1024, null=True, verbose_name='disclaimer'),
        ),
        migrations.AlterField(
            model_name='work',
            name='doctype',
            field=models.CharField(blank=True, help_text='FRBR doctype', max_length=64, verbose_name='doctype'),
        ),
        migrations.AlterField(
            model_name='work',
            name='frbr_uri',
            field=models.CharField(help_text='Used globally to identify this work', max_length=512, unique=True, verbose_name='FRBR URI'),
        ),
        migrations.AlterField(
            model_name='work',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='works', to='indigo_api.locality', verbose_name='locality'),
        ),
        migrations.AlterField(
            model_name='work',
            name='number',
            field=models.CharField(blank=True, help_text='FRBR number', max_length=512, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='work',
            name='parent_work',
            field=models.ForeignKey(blank=True, help_text='Parent (primary) work for subsidiary legislation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_works', to='indigo_api.work', verbose_name='parent (primary) work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='principal',
            field=models.BooleanField(default=False, help_text='Principal works are not simply repeals, amendments or commencements, and should have full text content.', verbose_name='principal'),
        ),
        migrations.AlterField(
            model_name='work',
            name='properties',
            field=models.JSONField(blank=True, default=dict, verbose_name='properties'),
        ),
        migrations.AlterField(
            model_name='work',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Date of publication', null=True, verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='publication_name',
            field=models.CharField(blank=True, help_text="Original publication's name, e.g. Government Gazette", max_length=255, null=True, verbose_name='publication name'),
        ),
        migrations.AlterField(
            model_name='work',
            name='publication_number',
            field=models.CharField(blank=True, help_text="Publication's sequence number, eg. gazette number", max_length=255, null=True, verbose_name='publication number'),
        ),
        migrations.AlterField(
            model_name='work',
            name='repealed_by',
            field=models.ForeignKey(blank=True, help_text='Work that repealed this work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repealed_works', to='indigo_api.work', verbose_name='repealed by'),
        ),
        migrations.AlterField(
            model_name='work',
            name='repealed_date',
            field=models.DateField(blank=True, help_text='Date of repeal of this work', null=True, verbose_name='repealed date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='stub',
            field=models.BooleanField(default=False, help_text='Stub works do not have content or points in time', verbose_name='stub'),
        ),
        migrations.AlterField(
            model_name='work',
            name='subtype',
            field=models.CharField(blank=True, help_text='FRBR subtype', max_length=512, null=True, verbose_name='subtype'),
        ),
        migrations.AlterField(
            model_name='work',
            name='taxonomies',
            field=models.ManyToManyField(related_name='works', to='indigo_api.VocabularyTopic', verbose_name='taxonomies'),
        ),
        migrations.AlterField(
            model_name='work',
            name='taxonomy_topics',
            field=models.ManyToManyField(blank=True, related_name='works', to='indigo_api.TaxonomyTopic', verbose_name='taxonomy topics'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(default='(untitled)', max_length=1024, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='work',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='work',
            name='updated_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_in_progress',
            field=models.BooleanField(default=True, help_text='Work in progress, to be approved', verbose_name='work in progress'),
        ),
        migrations.AlterField(
            model_name='workalias',
            name='alias',
            field=models.CharField(help_text='Alias e.g. Penal Code, etc', max_length=255, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='workalias',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='indigo_api.work', verbose_name='work'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='closed'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='indigo_api.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by user'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='indigo_api.locality', verbose_name='locality'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='priority',
            field=models.BooleanField(db_index=True, default=False, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='tasks',
            field=models.ManyToManyField(related_name='workflows', to='indigo_api.Task', verbose_name='tasks'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='updated_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by user'),
        ),
    ]
