# Generated by Django 3.2.13 on 2024-03-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0036_models_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomytopic',
            name='project',
            field=models.BooleanField(default=False, verbose_name='project'),
        ),
    ]
