# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-24 09:52
from django.db import migrations, models
import django.db.models.deletion


def create_works(apps, schema_editor):
    Document = apps.get_model("indigo_api", "Document")
    Work = apps.get_model("indigo_api", "Work")
    db_alias = schema_editor.connection.alias

    documents = Document.objects.using(db_alias).all()
    # works to create
    work_detail = {d.frbr_uri: d for d in documents}

    # create them
    works = [
        Work(
            frbr_uri=uri,
            title=d.title,
            country=d.country,
            publication_name=d.publication_name,
            publication_date=d.publication_date,
            publication_number=d.publication_number,
            commencement_date=d.commencement_date,
            assent_date=d.assent_date,
            deleted=d.deleted,
        ) for uri, d in work_detail.items()
    ]
    Work.objects.using(db_alias).bulk_create(works)


def delete_works(apps, schema_editor):
    Work = apps.get_model("indigo_api", "Work")
    db_alias = schema_editor.connection.alias
    Work.objects.using(db_alias).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0036_work'),
    ]

    operations = [
        migrations.RunPython(create_works, delete_works, elidable=True),
        migrations.AddField(
            model_name='document',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigo_api.Work', null=True),
            preserve_default=False,
        ),

        # link documents to works
        migrations.RunSQL(
            "UPDATE indigo_api_document d SET work_id = (SELECT id FROM indigo_api_work w WHERE d.frbr_uri = w.frbr_uri LIMIT 1)",
            migrations.RunSQL.noop,
            elidable=True),

        # make work column non-null
        migrations.AlterField(
            model_name='document',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigo_api.Work', null=False),
        ),
    ]
