# Generated by Django 3.2.13 on 2024-06-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    """ NOTE: for installs where the TaxonomyVocabulary, VocabularyTopic, and Workflow tables were manually deleted,
              this migration can safely -- and should -- be skipped.
              Other minor changes are in 0040 -- don't skip that one.
    """

    dependencies = [
        ('indigo_api', '0038_alter_subtype_abbreviation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vocabularytopic',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vocabularytopic',
            name='vocabulary',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='country',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='updated_by_user',
        ),
        migrations.RemoveField(
            model_name='work',
            name='taxonomies',
        ),
        migrations.DeleteModel(
            name='TaxonomyVocabulary',
        ),
        migrations.DeleteModel(
            name='VocabularyTopic',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
    ]
