# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 15:09
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0039_remove_work_draft'),
    ]

    operations = [
        migrations.RunSQL(
            migrations.RunSQL.noop,
            "UPDATE indigo_api_document SET commencement_date = w.commencement_date FROM indigo_api_work w WHERE w.id = work_id",
            elidable=True
        ),
        migrations.RemoveField(
            model_name='document',
            name='assent_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='commencement_date',
        ),
    ]
