# Generated by Django 3.2.13 on 2024-06-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0039_remove_old_taxonomies_workflows_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VocabularyTopic',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
    ]
