# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-08 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0040_remove_doc_assent_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='repealed_by',
            field=models.ForeignKey(help_text=b'Work that repealed this work', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indigo_api.Work'),
        ),
        migrations.AddField(
            model_name='work',
            name='repealed_date',
            field=models.DateField(blank=True, help_text=b'Date of repeal of this work', null=True),
        ),
    ]
