# Generated by Django 3.2.15 on 2024-07-14 08:59

from django.db import migrations, models
import indigo_api.models.citations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0040_remove_old_taxonomies_workflows_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Two letter country code, with optional locality code', max_length=1024, verbose_name='place')),
                ('frbr_uri', models.CharField(max_length=1024, validators=[indigo_api.models.citations.validate_frbr_uri], verbose_name='FRBR URI')),
                ('aliases', models.TextField(help_text='Aliases, one per line', verbose_name='aliases')),
            ],
            options={
                'verbose_name': 'Citation alias',
                'verbose_name_plural': 'Citation aliases',
                'ordering': ('frbr_uri',),
                'unique_together': {('place', 'frbr_uri')},
            },
        ),
    ]
