# Generated by Django 4.2.15 on 2024-09-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0042_backfill_task_comment_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('scope', models.CharField(choices=[('tasks', 'Tasks'), ('works', 'Works')], verbose_name='scope')),
                ('querystring', models.CharField(max_length=2048, verbose_name='querystring')),
            ],
            options={
                'verbose_name': 'quick link',
                'verbose_name_plural': 'quick links',
                'ordering': ['name'],
            },
        ),
    ]
