# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 18:33
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0043_doc_repeal_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='parent_work',
            field=models.ForeignKey(help_text=b'Parent related work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_works', to='indigo_api.Work'),
        ),
    ]
