# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 14:56
from __future__ import unicode_literals

from django.db import migrations
import arrow

from cobalt.act import FrbrUri


def create_amendments(apps, schema_editor):
    Document = apps.get_model("indigo_api", "Document")
    Work = apps.get_model("indigo_api", "Work")
    db_alias = schema_editor.connection.alias

    # ensure works existing for all amending documents
    documents = Document.objects.filter(deleted=False).using(db_alias).all()
    works = {w.frbr_uri: w for w in Work.objects.using(db_alias).all()}

    for doc in documents:
        for amendment in (doc.amendment_events or []):
            work = works.get(amendment['amending_uri'])

            if not work:
                # validate frbr_uri
                try:
                    FrbrUri.parse(amendment['amending_uri'])
                except ValueError:
                    continue
                date = arrow.get(amendment['date']).date()

                work = Work(
                    title=amendment['amending_title'],
                    frbr_uri=amendment['amending_uri'],
                    publication_date=date,
                )
                work.save()
                works[work.frbr_uri] = work


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0044_work_parent_work'),
    ]

    operations = [
        migrations.RunPython(create_amendments, migrations.RunPython.noop),
    ]
