# Generated by Django 4.2.15 on 2024-09-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0044_alter_savedsearch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomytopic',
            name='copy_from_principal',
            field=models.BooleanField(default=False, help_text='Copy this topic from principal works to works that amend, commence or repeal the principal work.', verbose_name='copy from principal work'),
        ),
    ]
