# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 14:56
from django.db import migrations
from iso8601 import parse_date

from cobalt.act import FrbrUri


def create_amendments(apps, schema_editor):
    Document = apps.get_model("indigo_api", "Document")
    Work = apps.get_model("indigo_api", "Work")
    Amendment = apps.get_model("indigo_api", "Amendment")
    db_alias = schema_editor.connection.alias

    # ensure works existing for all amending documents
    documents = Document.objects.filter(deleted=False).using(db_alias).all()
    works = {w.frbr_uri: w for w in Work.objects.using(db_alias).all()}

    for doc in documents:
        for amendment in (doc.amendment_events or []):
            work = works.get(amendment['amending_uri'])
            date = parse_date(amendment['date']).date()

            if not work:
                # validate frbr_uri
                try:
                    FrbrUri.parse(amendment['amending_uri'])
                except ValueError:
                    continue

                work = Work(
                    title=amendment['amending_title'],
                    frbr_uri=amendment['amending_uri'],
                    publication_date=date,
                )
                work.save()
                works[work.frbr_uri] = work

            # hard link the amendment to the work
            if not doc.work.amendments.filter(amending_work=work, date=date).exists():
                a = Amendment(date=date, amending_work=work, amended_work=doc.work)
                a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0045_amendment'),
    ]

    operations = [
        migrations.RunPython(create_amendments, migrations.RunPython.noop),
    ]
