# Generated by Django 4.2.15 on 2024-09-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0046_attachment_filenames_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('document', 'filename')},
        ),
    ]
