# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0047_remove_document_amendment_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='commencing_work',
            field=models.ForeignKey(help_text=b'Date that marked this work as commenced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='indigo_api.Work'),
        ),
    ]
