# Generated by Django 4.2.15 on 2024-10-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0047_alter_attachment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendment',
            name='verb',
            field=models.CharField(blank=True, default='amended', help_text="Replace with e.g. 'revised' as needed", verbose_name='verb'),
        ),
    ]
