# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-01 08:26
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0049_remove_deleted_works'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='work',
            name='commencing_work',
            field=models.ForeignKey(help_text=b'Date that marked this work as commenced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commenced_works', to='indigo_api.Work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='repealed_by',
            field=models.ForeignKey(help_text=b'Work that repealed this work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repealed_works', to='indigo_api.Work'),
        ),
    ]
