# Generated by Django 4.2.15 on 2025-01-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0049_accentedterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="to be shown in the document's drop-down menu", max_length=32, verbose_name='annotation title')),
                ('content', models.CharField(help_text="will always be wrapped in []s — don't include them again", max_length=512, verbose_name='annotation content')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_annotations', to='indigo_api.language', verbose_name='language')),
            ],
        ),
    ]
