# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-10 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0050_hard_delete_works'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amendment',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='document',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='publication_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='publication_number',
        ),
        migrations.AlterField(
            model_name='work',
            name='publication_date',
            field=models.DateField(blank=True, help_text=b'Date of publication', null=True),
        ),
    ]
