# Generated by Django 4.2.15 on 2025-04-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0050_commonannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='repealed_note',
            field=models.CharField(blank=True, help_text='Optional note giving extra detail about the repeal', max_length=512, null=True, verbose_name='repealed note'),
        ),
        migrations.AddField(
            model_name='work',
            name='repealed_verb',
            field=models.CharField(blank=True, help_text="Specify if it should be anything other than 'repealed' (the default)", max_length=256, null=True, verbose_name='repealed verb'),
        ),
    ]
