# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-06 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0051_publication_date_is_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'permissions': (('review', 'Can review work details'),)},
        ),
    ]
