# Generated by Django 4.2.15 on 2025-04-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0052_backfill_work_repealed_verb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='The Chapter number', max_length=32, null=True, verbose_name='number')),
                ('name', models.CharField(blank=True, default='chapter', help_text="Specify if it should be anything other than 'chapter' (the default)", max_length=64, verbose_name='name')),
                ('validity_start_date', models.DateField(blank=True, help_text='Date from which this Chapter number applied to the work', null=True, verbose_name='validity start date')),
                ('validity_end_date', models.DateField(blank=True, help_text='Date until which this Chapter number applied to the work', null=True, verbose_name='validity end date')),
                ('revision_name', models.CharField(blank=True, help_text='Name of the publication in which this Chapter number was assigned to the work', max_length=64, null=True, verbose_name='revision name')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_numbers', to='indigo_api.work', verbose_name='work')),
            ],
            options={
                'verbose_name': 'chapter number',
                'verbose_name_plural': 'chapter numbers',
                'ordering': ('-validity_start_date',),
            },
        ),
    ]
