# Generated by Django 4.2.15 on 2025-04-11 17:40

from django.conf import settings
from django.db import migrations


def move_chapter_numbers(apps, schema_editor):
    """ Move works' Chapter numbers in properties to separate objects.
    """
    Work = apps.get_model('indigo_api', 'Work')
    ChapterNumber = apps.get_model('indigo_api', 'ChapterNumber')
    place_properties = settings.INDIGO['WORK_PROPERTIES']

    for work in Work.objects.using('direct').all().only('properties').iterator():
        if work.properties:
            cap_strings = [p for p in work.properties if 'cap' in p]
            for cap_string in cap_strings:
                chapter_number = ChapterNumber(work=work, number=work.properties[cap_string])
                if cap_string != 'cap':
                    # add the description
                    place_code = work.country.country.iso.lower()
                    if work.locality:
                        place_code += f'-{work.locality.code}'
                    props = place_properties.get(place_code, {})
                    chapter_number.revision_name = props.get(cap_string)
                chapter_number.save()
                del work.properties[cap_string]
                work.save(update_fields=['properties'])


def move_chapter_numbers_back(apps, schema_editor):
    """ Move ChapterNumbers' numbers back into properties on their works. One per work only; will lose some information.
    """
    ChapterNumber = apps.get_model('indigo_api', 'ChapterNumber')

    for chapter_number in ChapterNumber.objects.using('direct').all().iterator():
        work = chapter_number.work
        if not work.properties.get('cap'):
            work.properties['cap'] = chapter_number.number
            work.save(update_fields=['properties'])


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0053_chapternumber'),
    ]

    operations = [
        migrations.RunPython(move_chapter_numbers, move_chapter_numbers_back, elidable=True)
    ]
