# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-28 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0053_work_view_perm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('publish_document', 'Can publish and edit non-draft documents'), ('view_published_document', 'Can view publish documents through the API'))},
        ),
    ]
