# Generated by Django 4.2.15 on 2025-10-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0054_backfill_chapter_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(default='(untitled)', max_length=1024, verbose_name='title'),
            preserve_default=False,
        ),
    ]
