# Generated by Django 4.2.15 on 2025-10-30 12:21

import django.db.models.deletion
from django.db import migrations, models


def backfill_main_commencement(apps, schema_editor):
    Work = apps.get_model('indigo_api', 'Work')
    Commencement = apps.get_model('indigo_api', 'Commencement')
    db_alias = schema_editor.connection.alias
    for work in Work.objects.using(db_alias).all():
        main_commencement = Commencement.objects.using(db_alias).filter(commenced_work=work, main=True).order_by('date').first()
        if main_commencement:
            work.main_commencement_id = main_commencement.id
            work.save(update_fields=['main_commencement'])


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0055_alter_work_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='main_commencement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indigo_api.commencement'),
        ),
        migrations.RunPython(backfill_main_commencement, migrations.RunPython.noop),
    ]
