# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0056_doc_requires_expression_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='commencing_work',
            field=models.ForeignKey(blank=True, help_text=b'Date that marked this work as commenced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commenced_works', to='indigo_api.Work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='parent_work',
            field=models.ForeignKey(blank=True, help_text=b'Parent related work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_works', to='indigo_api.Work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='repealed_by',
            field=models.ForeignKey(blank=True, help_text=b'Work that repealed this work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repealed_works', to='indigo_api.Work'),
        ),
    ]
