# Generated by Django 5.0 on 2026-02-02 16:14

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0001_squashed_0056_work_main_commencement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmendmentInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(default='new', max_length=50, verbose_name='state')),
                ('amending_provision', models.CharField(blank=True, max_length=2048, null=True, verbose_name='amending provision')),
                ('title', models.CharField(blank=True, max_length=4096, null=True, verbose_name='title')),
                ('page_number', models.IntegerField(blank=True, null=True, verbose_name='page number')),
                ('provision_name', models.CharField(blank=True, max_length=4096, null=True, verbose_name='provision name')),
                ('amendment_instruction', models.TextField(blank=True, null=True, verbose_name='amendment instruction')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='applied at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='indigo_api.amendment', verbose_name='amendment')),
                ('applied_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='applied by')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'ordering': ['page_number', 'provision_name'],
            },
        ),
    ]
