# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0002_auto_20141008_0947'),
        ('countries_plus', '0005_auto_20160224_1804'),
        ('indigo_api', '0057_blanks'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='countries_plus.Country')),
            ],
            options={
                'ordering': ['country__name'],
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='languages_plus.Language')),
            ],
            options={
                'ordering': ['language__name_en'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='primary_language',
            field=models.ForeignKey(help_text=b'Primary language for this country', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='indigo_api.Language'),
        ),
    ]

    operations = [
        # By running only state operations, we are making Django think it has
        # applied this migration to the database. In reality, we renamed a
        # "indigo_app_(language|country)" tables to "indigo_api_(language|country)" earlier.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
