# Generated by Django 5.0 on 2026-02-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0057_amendmentinstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendmentinstruction',
            name='amended_provision_id',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='amended provision id'),
        ),
        migrations.AddField(
            model_name='amendmentinstruction',
            name='amended_text',
            field=models.TextField(blank=True, null=True, verbose_name='amended text'),
        ),
        migrations.AddField(
            model_name='amendmentinstruction',
            name='amended_xml',
            field=models.TextField(blank=True, null=True, verbose_name='amended xml'),
        ),
        migrations.AddField(
            model_name='amendmentinstruction',
            name='final_amended_text',
            field=models.TextField(blank=True, null=True, verbose_name='final amended text'),
        ),
        migrations.AddField(
            model_name='amendmentinstruction',
            name='final_amended_xml',
            field=models.TextField(blank=True, null=True, verbose_name='final amended text'),
        ),
    ]
