# Generated by Django 2.2.12 on 2020-10-30 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('indigo_api', '0059_colophon_new_country'), ('indigo_api', '0060_colophon_country'), ('indigo_api', '0061_colophon_new_country_required'), ('indigo_api', '0062_colophon_remove_old_country'), ('indigo_api', '0063_document_language_obj'), ('indigo_api', '0064_migrate_language'), ('indigo_api', '0065_remove_old_language'), ('indigo_api', '0066_doc_language_required'), ('indigo_api', '0067_remove_document_country'), ('indigo_api', '0068_work_country_obj'), ('indigo_api', '0069_populate_work_country_obj'), ('indigo_api', '0070_remove_old_work_country'), ('indigo_api', '0071_work_country_required')]

    dependencies = [
        ('indigo_app', '0001_squashed_0015_point_at_moved_language_country'),
        ('reversion', '0002_auto_20141216_1509'),
        ('indigo_api', '0058_import_language_country_from_indigo_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Colophon',
            name='country',
        ),
        migrations.RemoveField(
            model_name='Document',
            name='language',
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.ForeignKey(help_text=b'Language this document is in.', on_delete=django.db.models.deletion.PROTECT, to='indigo_api.Language'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='country',
        ),
        migrations.AddField(
            model_name='colophon',
            name='country',
            field=models.ForeignKey(help_text=b'Which country does this colophon apply to?', on_delete=django.db.models.deletion.CASCADE, to='indigo_api.Country'),
        ),
        migrations.RemoveField(
            model_name='Work',
            name='country',
        ),
        migrations.AddField(
            model_name='work',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indigo_api.Country'),
        ),
    ]
