# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 18:25
from __future__ import unicode_literals

from django.db import migrations


def populate_new_country(apps, schema_editor):
    """ Update colophon.new_country to use the indigo_api.Country model,
    not the countries_plus model.
    """
    Colophon = apps.get_model("indigo_api", "Colophon")
    Country = apps.get_model("indigo_api", "Country")
    db_alias = schema_editor.connection.alias

    countries = {c.country.iso: c for c in Country.objects.using(db_alias).all()}

    for colophon in Colophon.objects.using(db_alias).all():
        if colophon.country:
            colophon.new_country = countries.get(colophon.country.iso)

        if not colophon.new_country:
            # arbitrary country
            colophon.new_country = countries.values()[0]

        colophon.save()


def populate_old_country(apps, schema_editor):
    """ Rollback populate_new_country.
    """
    Colophon = apps.get_model("indigo_api", "Colophon")
    db_alias = schema_editor.connection.alias

    for colophon in Colophon.objects.using(db_alias).all():
        colophon.country = colophon.new_country.country
        colophon.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0059_colophon_new_country'),
    ]

    operations = [
        migrations.RunPython(populate_new_country, populate_old_country),
    ]
