# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 19:35
from __future__ import unicode_literals

from django.db import migrations


def populate_language(apps, schema_editor):
    Document = apps.get_model("indigo_api", "Document")
    Language = apps.get_model("indigo_api", "Language")
    db_alias = schema_editor.connection.alias

    languages = {l.language.iso_639_2B: l for l in Language.objects.using(db_alias).all()}

    for document in Document.objects.using(db_alias).all():
        # if this raises a key error, use the admin interface to create
        # a Language object for the missing language
        document.language_obj = languages[document.language]
        document.save(update_fields=['language_obj'])


def revert_language(apps, schema_editor):
    Document = apps.get_model("indigo_api", "Document")
    db_alias = schema_editor.connection.alias

    for document in Document.objects.using(db_alias).all():
        document.language = document.language_obj.language.iso_639_2B
        document.save(update_fields=['language'])


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0063_document_language_obj'),
    ]

    operations = [
        migrations.RunPython(populate_language, revert_language),
    ]
