# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0064_migrate_language'),
    ]

    operations = [
        migrations.RemoveField('Document', 'language'),
        migrations.RenameField('Document', 'language_obj', 'language'),
    ]
