# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0065_remove_old_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.ForeignKey(help_text=b'Language this document is in.', null=False, on_delete=django.db.models.deletion.PROTECT, to='indigo_api.Language'),
        ),
    ]
