# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0066_doc_language_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='country',
        ),
    ]
