# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0067_remove_document_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='country_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='indigo_api.Country'),
        ),
    ]
