# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0069_populate_work_country_obj'),
    ]

    operations = [
        migrations.RemoveField('Work', 'country'),
        migrations.RenameField('Work', 'country_obj', 'country'),
    ]
