# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0071_work_country_required'),
        ('indigo_app', '0018_rename_locality_table'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Local name of this locality', max_length=512)),
                ('code', models.CharField(help_text=b'Unique code of this locality (used in the FRBR URI)', max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigo_api.Country')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Localities',
            },
        ),
        migrations.AlterUniqueTogether(
            name='locality',
            unique_together=set([('country', 'code')]),
        ),
    ]

    operations = [
        # By running only state operations, we are making Django think it has
        # applied this migration to the database. In reality, we renamed a
        # "indigo_app_locality" tables to "indigo_api_locality" earlier.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
