# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0073_renamed_localities_related'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('publish_document', 'Can publish and edit non-draft documents'), ('view_published_document', 'Can view publish documents through the API'), ('view_document_xml', 'Can view the source XML of documents'))},
        ),
    ]
