# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 09:39
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0075_work_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='indigo_api.Locality'),
        ),
    ]
