# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import indigo_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0076_work_locality_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=indigo_api.models.publication_document_filename)),
                ('size', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_document', to='indigo_api.Work')),
            ],
        ),
    ]
