# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 14:09
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0078_task_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('submit_task', 'Can submit an open task for review'), ('reopen_task', 'Can reopen a task that is closed or cancelled'), ('cancel_task', 'Can cancel a task that is open or has been submitted for review'), ('close_task', 'Can close a task that has been submitted for review'), ('unsubmit_task', 'Can reopen a task that has been submitted for review'), ('resubmit_task', 'Can resubmit a task for review that has been cancelled or closed'))},
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=django_fsm.FSMField(default=b'open', max_length=50),
        ),
    ]
