# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0078_task_workflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated_by',
            new_name='updated_by_user',
        ),
    ]
