# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0081_task_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklabel',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_cancelled_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_cancelled_by_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_closed_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_closed_by_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_reopened_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_reopened_by_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_submitted_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_submitted_by_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_unsubmitted_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_unsubmitted_by_user',
        ),
    ]
