# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0082_task_fields_removed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklabel',
            options={'ordering': ['title']},
        ),
    ]
