# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0083_task_label_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='indigo_api.Country'),
        ),
        migrations.AlterField(
            model_name='work',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='works', to='indigo_api.Locality'),
        ),
    ]
