# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 10:23
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indigo_api', '0085_annotation_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'permissions': (('review_work', 'Can review work details'),)},
        ),
        migrations.AddField(
            model_name='workflow',
            name='country',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='indigo_api.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='indigo_api.Locality'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='updated_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
