# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 08:57
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indigo_api', '0086_workflows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'permissions': (('close_workflow', 'Can close a workflow'),)},
        ),
        migrations.AddField(
            model_name='workflow',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='closed_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
