# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 14:25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0087_workflows_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
