# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0088_workflow_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='closed_by_user',
        ),
    ]
