# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-22 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0090_publication_doc_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationdocument',
            name='trusted_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
