# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 14:11
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indigo_api', '0090_publication_doc_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
