# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 13:31
from django.db import migrations, models


def populate_stub(apps, schema_editor):
    Document = apps.get_model("indigo_api", "Document")
    Work = apps.get_model("indigo_api", "Work")
    db_alias = schema_editor.connection.alias

    for doc in Document.objects.using(db_alias).filter(stub=True).all():
        doc.work.stub = True
        doc.work.save()

    for work in Work.objects.using(db_alias).all():
        if not work.amendments.exists() and not work.document_set.exists():
            work.stub = True
            work.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0092_publicationdocument_trusted_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='stub',
            field=models.BooleanField(default=False, help_text=b'Stub works do not have content or points in time'),
        ),
        migrations.RunPython(populate_stub, migrations.RunPython.noop, elidable=True),
    ]
