# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 14:48
from django.db import migrations


def populate_stub(apps, schema_editor):
    Work = apps.get_model("indigo_api", "Work")
    db_alias = schema_editor.connection.alias

    for work in Work.objects.using(db_alias).filter(stub=True).all():
        for doc in work.document_set.all():
            doc.stub = True
            work.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0093_work_stub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='stub',
        ),
        migrations.RunPython(migrations.RunPython.noop, populate_stub, elidable=True),
    ]
