# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 12:45
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0095_pub_doc_size_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=1024)),
                ('value', models.CharField(max_length=1024)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='indigo_api.Work')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='workproperty',
            unique_together=set([('work', 'key')]),
        ),
    ]
