# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indigo_api', '0097_workproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='closed_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
