# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 08:44
from django.db import migrations
from django.contrib.contenttypes.models import ContentType


def populate_closed_by(apps, schema_editor):
    Action = apps.get_model("actstream", "action")
    Task = apps.get_model("indigo_api", "Task")
    db_alias = schema_editor.connection.alias

    content_type = ContentType.objects.get_for_model(Task)

    # backfill task.closed_by_user
    for action in Action.objects.using(db_alias).filter(verb='closed', action_object_content_type_id=content_type.pk):
        Task.objects.filter(pk=action.action_object_object_id).update(closed_by_user_id=action.actor_object_id)


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0098_task_closed_by_user_code'),
    ]

    operations = [
        migrations.RunPython(populate_closed_by, migrations.RunPython.noop, elidable=True),
    ]
