# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 11:59
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0100_remove_whitespace'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(help_text=b'Organisation managing this taxonomy', max_length=30, unique=True)),
                ('name', models.CharField(help_text=b'Short name for this taxonomy, under this authority', max_length=30, unique=True)),
                ('slug', models.SlugField(help_text=b'Code used in the API', unique=True)),
                ('title', models.CharField(help_text=b'Friendly, full title for the taxonomy', max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Taxonomy',
                'verbose_name_plural': 'Taxonomies',
            },
        ),
        migrations.CreateModel(
            name='VocabularyTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1', models.CharField(max_length=30)),
                ('level_2', models.CharField(blank=True, help_text=b'(optional)', max_length=30, null=True)),
                ('taxonomy_vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='indigo_api.TaxonomyVocabulary')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='taxonomies',
            field=models.ManyToManyField(related_name='works', to='indigo_api.VocabularyTopic'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabularytopic',
            unique_together=set([('level_1', 'level_2', 'taxonomy_vocabulary')]),
        ),
    ]
