# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 10:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0101_taxonomies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ('filename',)},
        ),
        migrations.AlterModelOptions(
            name='documentactivity',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='subtype',
            options={'ordering': ('name',), 'verbose_name': 'Document subtype'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ('title',), 'permissions': (('close_workflow', 'Can close a workflow'),)},
        ),
        migrations.AddField(
            model_name='task',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={b'points': 12}),
        ),
    ]
