# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 09:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0102_changes_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
