# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 17:06
from django.db import migrations
from django.contrib.contenttypes.models import ContentType


def populate_last_assigned_to(apps, schema_editor):
    Action = apps.get_model("actstream", "action")
    Task = apps.get_model("indigo_api", "Task")
    db_alias = schema_editor.connection.alias

    content_type = ContentType.objects.get_for_model(Task)

    # backfill task.last_assigned_to based on the last user to submit it
    for action in Action.objects.using(db_alias).filter(verb='submitted', action_object_content_type_id=content_type.pk).order_by('timestamp'):
        Task.objects.filter(pk=action.action_object_object_id).update(last_assigned_to_id=action.actor_object_id)


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0104_task_closed_at'),
    ]

    operations = [
        migrations.RunPython(populate_last_assigned_to, migrations.RunPython.noop, elidable=True),
    ]
