# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-05 06:57
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indigo_api', '0105_backfill_task_last_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='closed_by_user',
            new_name='reviewed_by_user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='last_assigned_to',
            new_name='submitted_by_user',
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewed_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='submitted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='submitted_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
