# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 09:19
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0106_rename_task_fields'),
    ]

    operations = [
        migrations.RenameField('vocabularytopic', 'taxonomy_vocabulary', 'vocabulary'),
        migrations.AlterUniqueTogether(
            name='vocabularytopic',
            unique_together=set([('level_1', 'level_2', 'vocabulary')]),
        ),
    ]
