# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-28 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0107_taxonomy_tweaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularytopic',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='indigo_api.TaxonomyVocabulary'),
        ),
    ]
