# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0107_auto_20190716_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='taxonomies',
            field=models.ManyToManyField(related_name='taxonomies', to='indigo_api.VocabularyTopic'),
        ),
    ]
