# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-01 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0109_backfill_place_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendment',
            name='amended_work',
            field=models.ForeignKey(help_text='Work amended.', on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='indigo_api.Work'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='amending_work',
            field=models.ForeignKey(help_text='Work making the amendment.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indigo_api.Work'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='date',
            field=models.DateField(help_text='Date of the amendment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(db_index=True, help_text='Unique attachment filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='colophon',
            name='country',
            field=models.ForeignKey(help_text='Which country does this colophon apply to?', on_delete=django.db.models.deletion.CASCADE, to='indigo_api.Country'),
        ),
        migrations.AlterField(
            model_name='colophon',
            name='name',
            field=models.CharField(help_text='Name of this colophon', max_length=1024),
        ),
        migrations.AlterField(
            model_name='country',
            name='primary_language',
            field=models.ForeignKey(help_text='Primary language for this country', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='indigo_api.Language'),
        ),
        migrations.AlterField(
            model_name='document',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Has this document been deleted?'),
        ),
        migrations.AlterField(
            model_name='document',
            name='draft',
            field=models.BooleanField(default=True, help_text="Drafts aren't available through the public API"),
        ),
        migrations.AlterField(
            model_name='document',
            name='expression_date',
            field=models.DateField(help_text='Date of publication or latest amendment'),
        ),
        migrations.AlterField(
            model_name='document',
            name='frbr_uri',
            field=models.CharField(default='/', help_text='Used globally to identify this work', max_length=512),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.ForeignKey(help_text='Language this document is in.', on_delete=django.db.models.deletion.PROTECT, to='indigo_api.Language'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='code',
            field=models.CharField(help_text='Unique code of this locality (used in the FRBR URI)', max_length=100),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(help_text='Local name of this locality', max_length=512),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='abbreviation',
            field=models.CharField(help_text='Short abbreviation to use in FRBR URI. No punctuation.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='name',
            field=models.CharField(help_text='Name of the document subtype', max_length=1024),
        ),
        migrations.AlterField(
            model_name='task',
            name='changes_requested',
            field=models.BooleanField(default=False, help_text='Have changes been requested on this task?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='closed_at',
            field=models.DateTimeField(help_text='When the task was marked as done or cancelled.', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=django_fsm.FSMField(default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='authority',
            field=models.CharField(help_text='Organisation managing this taxonomy', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='name',
            field=models.CharField(help_text='Short name for this taxonomy, under this authority', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='slug',
            field=models.SlugField(help_text='Code used in the API', unique=True),
        ),
        migrations.AlterField(
            model_name='taxonomyvocabulary',
            name='title',
            field=models.CharField(help_text='Friendly, full title for the taxonomy', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vocabularytopic',
            name='level_2',
            field=models.CharField(blank=True, help_text='(optional)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularytopic',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='indigo_api.TaxonomyVocabulary'),
        ),
        migrations.AlterField(
            model_name='work',
            name='commencing_work',
            field=models.ForeignKey(blank=True, help_text='Date that marked this work as commenced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commenced_works', to='indigo_api.Work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='parent_work',
            field=models.ForeignKey(blank=True, help_text='Parent related work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_works', to='indigo_api.Work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Date of publication', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='repealed_by',
            field=models.ForeignKey(blank=True, help_text='Work that repealed this work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repealed_works', to='indigo_api.Work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='repealed_date',
            field=models.DateField(blank=True, help_text='Date of repeal of this work', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='stub',
            field=models.BooleanField(default=False, help_text='Stub works do not have content or points in time'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(default='(untitled)', max_length=1024, null=True),
        ),
    ]
