# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-19 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0110_django3_tweaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesettings',
            name='styleguide_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
