# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-12 11:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0112_arbitrary_expression_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
