# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-12 11:58
from __future__ import unicode_literals

from django.db import migrations


def migrate_work_properties(apps, schema_editor):
    """ Copy work properties from WorkProperty objects into work.properties dict.
    """
    WorkProperty = apps.get_model("indigo_api", "WorkProperty")
    db_alias = schema_editor.connection.alias
    works = set()

    for prop in WorkProperty.objects.using(db_alias).all():
        prop.work.properties[prop.key] = prop.value
        works.add(prop.work)

    for work in works:
        work.save()


def unmigrate_work_properties(apps, schema_editor):
    """ Copy work properties back into WorkProperty objects.
    """
    WorkProperty = apps.get_model("indigo_api", "WorkProperty")
    Work = apps.get_model("indigo_api", "Work")
    db_alias = schema_editor.connection.alias

    for work in Work.objects.using(db_alias).all():
        if work.properties:
            for key, val in work.properties.items():
                WorkProperty.objects.create(work=work, key=key, value=val)


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0113_work_properties'),
    ]

    operations = [
        migrations.RunPython(migrate_work_properties, unmigrate_work_properties, elidable=True),
    ]
