# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-22 14:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0115_drop_work_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'permissions': (('review_work', 'Can review work details'), ('bulk_add_work', 'Can import works in bulk'))},
        ),
        migrations.AlterField(
            model_name='work',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
