# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-31 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0116_work_props_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendment',
            name='amending_work',
            field=models.ForeignKey(help_text='Work making the amendment.', on_delete=django.db.models.deletion.CASCADE, related_name='amendments_made', to='indigo_api.Work'),
        ),
    ]
