# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-25 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0117_amendments_made'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'permissions': (('review_work', 'Can review work details'), ('bulk_add_work', 'Can import works in bulk'), ('bulk_export_work', 'Can export works in bulk'))},
        ),
    ]
