# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-12 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0117_amendments_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='commenced',
            field=models.BooleanField(default=False, help_text='Has this work commenced? (Date may be unknown)'),
        ),
    ]
