# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-12 13:23
from __future__ import unicode_literals

from django.db import migrations


def migrate_work_commenced(apps, schema_editor):
    """ Mark all existing works as 'commenced' if they have either a commencement date or a commencing work.
    """
    Work = apps.get_model("indigo_api", "Work")
    db_alias = schema_editor.connection.alias
    for work in Work.objects.using(db_alias).all():
        if work.commencement_date or work.commencing_work:
            work.commenced = True
            work.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0118_work_commenced'),
    ]

    operations = [
        migrations.RunPython(migrate_work_commenced, migrations.RunPython.noop, elidable=True),
    ]
