# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-28 07:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indigo_api', '0123_remove_task_anchor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commencement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Date of the commencement, or null if listed provisions are uncommenced', null=True)),
                ('main', models.BooleanField(default=False, help_text='This commencement date is the date on which most of the provisions of the principal work come into force')),
                ('all_provisions', models.BooleanField(default=False, help_text='All provisions of this work commenced on this date')),
                ('provisions_list', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='commencement',
            name='commenced_work',
            field=models.ForeignKey(help_text='Principal work being commenced', on_delete=django.db.models.deletion.CASCADE, related_name='commencements', to='indigo_api.Work'),
        ),
        migrations.AddField(
            model_name='commencement',
            name='commencing_work',
            field=models.ForeignKey(help_text='Work that provides the commencement date for the principal work', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commencements_made', to='indigo_api.Work'),
        ),
        migrations.AddField(
            model_name='commencement',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commencement',
            name='updated_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='commencement',
            unique_together=set([('commenced_work', 'commencing_work', 'date')]),
        ),
    ]
