# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-26 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0125_migrate_commencements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='commencement_date',
        ),
        migrations.RemoveField(
            model_name='work',
            name='commencing_work',
        ),
    ]
