# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-14 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0126_drop_commencement_details_from_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uncommencedprovisions',
            name='provisions',
        ),
        migrations.AlterField(
            model_name='commencement',
            name='date',
            field=models.DateField(blank=True, help_text='Date of the commencement, or null if it is unknown', null=True),
        ),
    ]
