# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-26 14:02
from __future__ import unicode_literals

from django.contrib.auth.models import Group
from django.db import migrations
from pinax.badges.models import BadgeAward


def rename_badges(apps, schema_editor):
    """ Rename badges, and delete old security groups
    """
    slugs = [
        ('drafter', 'editor'),
        ('senior-drafter', 'reviewer'),
    ]
    security_groups = ['Drafter Badge', 'Senior Drafter Badge']

    for old, new in slugs:
        BadgeAward.objects.filter(slug=old).update(slug=new)

    for g in security_groups:
        try:
            group = Group.objects.get(name=g)
            group.delete()
        except Group.DoesNotExist:
            pass


def unrename_badges(apps, schema_editor):
    """ Rename badges, and delete new security groups
    """
    slugs = [
        ('editor', 'drafter'),
        ('reviewer', 'senior-drafter'),
    ]
    slugs_to_delete = ['researcher', 'super-reviewer']
    security_groups = ['Editor Badge', 'Reviewer Badge', 'Super Reviewer Badge', 'Researcher Badge']

    for new, old in slugs:
        BadgeAward.objects.filter(slug=new).update(slug=old)

    for s in slugs_to_delete:
        BadgeAward.objects.filter(slug=s).delete()

    for g in security_groups:
        try:
            group = Group.objects.get(name=g)
            group.delete()
        except Group.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0127_add_close_any_task_permission'),
    ]

    operations = [
        migrations.RunPython(rename_badges, unrename_badges),
    ]
