# Generated by Django 2.2.13 on 2020-10-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0135_auto_20201023_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='search_text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='search_vector',
        ),
    ]
