# Generated by Django 2.2.13 on 2020-10-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0136_drop_search'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP FUNCTION IF EXISTS search_text_trigger() CASCADE",
        )
    ]
