# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='A short bio', max_length=1024)),
                ('qualifications', models.TextField(help_text='Qualifications', max_length=512)),
                ('skills', models.CharField(help_text='Skills', max_length=256)),
                ('organisations', models.CharField(help_text='Organisation(s)', max_length=256)),
                ('specialisations', models.CharField(help_text='Specialisation(s)', max_length=256)),
                ('areas_of_law', models.CharField(help_text='Area(s) of law', max_length=256)),
                ('profile_photo', models.ImageField(upload_to=b'')),
                ('twitter_profile', models.URLField()),
                ('linkedin_profile', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
