# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', help_text='A short bio', null=True)),
                ('qualifications', models.TextField(blank=True, default='', help_text='Qualifications', null=True)),
                ('skills', models.TextField(blank=True, default='', help_text='Skills', null=True)),
                ('organisations', models.TextField(blank=True, default='', help_text='Organisation(s)', null=True)),
                ('specialisations', models.TextField(blank=True, default='', help_text='Specialisation(s)', null=True)),
                ('areas_of_law', models.CharField(blank=True, default='', help_text='Area(s) of law', max_length=256, null=True)),
                ('profile_photo', models.ImageField(null=True, upload_to=b'')),
                ('twitter_username', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('linkedin_profile', models.URLField(blank=True, default='', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
