# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def create_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model('indigo_social', 'UserProfile')
    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)

def delete_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model('indigo_social', 'UserProfile')
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indigo_social', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, delete_user_profiles),
    ]
