# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='areas_of_law',
            field=models.CharField(blank=True, help_text='Area(s) of law', max_length=256),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short bio', max_length=1024),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisations',
            field=models.TextField(blank=True, help_text='Organisation(s)', max_length=256),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Qualifications', max_length=512),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills', max_length=256),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialisations',
            field=models.TextField(blank=True, help_text='Specialisation(s)', max_length=256),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_profile',
            field=models.URLField(blank=True),
        ),
    ]
