# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_social', '0002_createuserprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
