# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-28 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import indigo_social.models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_social', '0003_auto_20190329_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=indigo_social.models.user_directory_path),
        ),
    ]
