# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-16 09:26
from __future__ import unicode_literals

import random
import string

from django.core.files import File
from django.db import migrations

from urllib.request import urlretrieve, urlcleanup


def import_google_profile_pictures(apps, schema_editor):
    SocialAccount = apps.get_model('socialaccount', 'SocialAccount')
    UserProfile = apps.get_model('indigo_social', 'UserProfile')

    def fetch_and_save_profile_photo(user_profile, url):
        try:
            name, _ = urlretrieve(url)
            user_profile.profile_photo.save(name, File(open(name, 'rb')))
            user_profile.profile_photo_nonce = ''.join(random.sample(string.ascii_lowercase, 8))
            user_profile.save()
        finally:
            urlcleanup()

    for socialaccount in SocialAccount.objects.filter(provider='google').distinct('user_id'):
        try:
            user_profile = UserProfile.objects.get(user=socialaccount.user)
            url = socialaccount.extra_data.get('picture')
            fetch_and_save_profile_photo(user_profile, url)

        except UserProfile.DoesNotExist:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_social', '0004_add_profile_photo_nonce'),
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.RunPython(import_google_profile_pictures, reverse_code=migrations.RunPython.noop)
    ]
