# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-15 08:46
from __future__ import unicode_literals

from django.core.files import File
from django.db import migrations

from urllib.request import urlretrieve, urlcleanup


def import_google_profile_pictures(apps, schema_editor):
	SocialAccount = apps.get_model('allauth.socialaccount', 'SocialAccount')
	UserProfile = apps.get_model('indigo_social', 'UserProfile')

	def fetch_and_save_profile_photo(user_profile, url):
	    try:
	        name, _ = urlretrieve(url)
	        user_profile.profile_photo.save(name, File(open(name, 'rb')))
	    finally:
	        urlcleanup()

	for socialaccount in SocialAccount.objects.filter(provider='google').distinct('user_id'):
		user_profile = UserProfile.objects.get(user=socialaccount.user)
		url = socialaccount.extra_data.get('picture')
		fetch_and_save_profile_photo(user_profile, url)
	

class Migration(migrations.Migration):

    dependencies = [
        ('indigo_social', '0004_modify_profile_photo_upload_field'),
    ]

    operations = [
    	migrations.RunPython(import_google_profile_pictures, reverse_code=migrations.RunPython.noop)
    ]
