# Generated by Django 3.2.13 on 2023-02-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_social', '0005_import_google_profile_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('audit_user_activity', 'Can audit user activity'),)},
        ),
    ]
