# Generated by Django 3.2.15 on 2024-02-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_social', '0006_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('audit_user_activity', 'Can audit user activity'), ('use_indigo', 'Can use the Indigo application in general'))},
        ),
    ]
