# Generated by Django 3.2.15 on 2024-03-07 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import indigo_social.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indigo_social', '0006_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='areas_of_law',
            field=models.CharField(blank=True, default='', help_text='Areas of law', max_length=256, null=True, verbose_name='areas of law'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='A short bio', null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, default='', null=True, verbose_name='linkedin profile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisations',
            field=models.TextField(blank=True, default='', help_text='Organisations', null=True, verbose_name='organisations'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=indigo_social.models.user_profile_photo_path, verbose_name='profile photo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo_nonce',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='profile photo nonce'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qualifications',
            field=models.TextField(blank=True, default='', help_text='Qualifications', null=True, verbose_name='qualifications'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Skills', null=True, verbose_name='skills'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialisations',
            field=models.TextField(blank=True, default='', help_text='Specialisations', null=True, verbose_name='specialisations'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_username',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='twitter username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
