# Generated by Django 4.2.15 on 2024-08-12 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indigo_social', '0007_models_i18n'),
    ]

    replaces = [
        ('pinax_badges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_earned',
                                           to=settings.AUTH_USER_MODEL)),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'pinax_badges_badgeaward',
            },
        ),
    ]
