# Generated by Django 4.2.15 on 2024-08-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_social', '0007_models_i18n'),
    ]

    replaces = [
        ('pinax_badges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pinax_badges__badgeaward',
                'managed': False,
            },
        ),
    ]
