# Generated by Django 2.2.12 on 2020-10-29 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('indigo_app', '0001_initial'), ('indigo_app', '0002_languages'), ('indigo_app', '0003_subtype'), ('indigo_app', '0004_country'), ('indigo_app', '0005_delete_subtype'), ('indigo_app', '0006_auto_20150918_1515'), ('indigo_app', '0007_editor'), ('indigo_app', '0008_auto_20160111_1844'), ('indigo_app', '0009_publication'), ('indigo_app', '0010_accepted_terms'), ('indigo_app', '0011_country_primary_language'), ('indigo_app', '0012_country_set_primary_language'), ('indigo_app', '0013_country_force_primary_language'), ('indigo_app', '0014_rename_language_country_tables'), ('indigo_app', '0015_point_at_moved_language_country'), ('indigo_app', '0016_remove_moved_language_country_models'), ('indigo_app', '0017_auto_20180911_1126'), ('indigo_app', '0018_rename_locality_table'), ('indigo_app', '0019_remove_moved_locality_model'), ('indigo_app', '0020_editor_permitted_countries'), ('indigo_app', '0021_auto_20201023_1407')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this publication', max_length=512)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigo_api.Country')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indigo_api.Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('permitted_countries', models.ManyToManyField(blank=True, help_text='Countries the user can work with.', related_name='editors', to='indigo_api.Country')),
            ],
        ),
    ]
