# Generated by Django 2.2.12 on 2020-10-29 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('indigo_app', '0001_initial'), ('indigo_app', '0002_languages'), ('indigo_app', '0003_subtype'), ('indigo_app', '0004_country'), ('indigo_app', '0005_delete_subtype'), ('indigo_app', '0006_auto_20150918_1515'), ('indigo_app', '0007_editor'), ('indigo_app', '0008_auto_20160111_1844'), ('indigo_app', '0009_publication'), ('indigo_app', '0010_accepted_terms'), ('indigo_app', '0011_country_primary_language'), ('indigo_app', '0012_country_set_primary_language'), ('indigo_app', '0013_country_force_primary_language'), ('indigo_app', '0014_rename_language_country_tables'), ('indigo_app', '0015_point_at_moved_language_country')]

    initial = True

    dependencies = [
        ('languages_plus', '0002_auto_20141008_0947'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries_plus', '0002_auto_20150120_2225'),
        ('indigo_api', '0001_squashed_0058_import_language_country_from_indigo_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='countries_plus.Country')),
            ],
            options={
                'ordering': ['country__name'],
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='languages_plus.Language')),
            ],
            options={
                'ordering': ['language__name_en'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Name of this publication', max_length=512, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigo_app.Country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indigo_app.Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('accepted_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='primary_language',
            field=models.ForeignKey(help_text=b'Primary language for this country', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='indigo_app.Language'),
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Local name of this locality', max_length=512)),
                ('code', models.CharField(help_text=b'Unique code of this locality (used in the FRBR URI)', max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigo_app.Country')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Localities',
                'unique_together': {('country', 'code')},
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='country',
                    table='indigo_api_country',
                ),
                migrations.AlterModelTable(
                    name='language',
                    table='indigo_api_language',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='editor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indigo_api.Country'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigo_api.Country'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigo_api.Country'),
        ),
    ]
