# Generated by Django 3.2.15 on 2024-03-07 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indigo_api', '0036_models_i18n'),
        ('indigo_app', '0002_editor_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={'verbose_name': 'editor', 'verbose_name_plural': 'editors'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['name'], 'verbose_name': 'publication', 'verbose_name_plural': 'publications'},
        ),
        migrations.AlterField(
            model_name='editor',
            name='accepted_terms',
            field=models.BooleanField(default=False, verbose_name='accepted terms'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indigo_api.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='language',
            field=models.CharField(default='en-us', help_text='Preferred language', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='permitted_countries',
            field=models.ManyToManyField(blank=True, help_text='Countries the user can work with.', related_name='editors', to='indigo_api.Country', verbose_name='permitted countries'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigo_api.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(help_text='Name of this publication', max_length=512, verbose_name='name'),
        ),
    ]
