# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 10:30
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_app', '0008_auto_20160111_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Name of this publication', max_length=512, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indigo_app.Country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
