# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_app', '0009_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
