# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0071_work_country_required'),
        ('indigo_app', '0016_remove_moved_language_country_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(help_text=b'Name of this publication', max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set([('country', 'name')]),
        ),
    ]
