# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_app', '0017_auto_20180911_1126'),
    ]

    database_operations = [
        migrations.AlterModelTable('locality', 'indigo_api_locality'),
    ]

    # Don't modify the Django 'state' yet
    state_operations = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
