# Generated by Django 2.2.12 on 2020-10-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('indigo_app', '0019_remove_moved_locality_model'), ('indigo_app', '0020_editor_permitted_countries'), ('indigo_app', '0021_auto_20201023_1407')]

    dependencies = [
        ('indigo_api', '0072_import_locality_from_indigo_app'),
        ('indigo_app', '0018_rename_locality_table'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Locality',
                ),
            ],
        ),
        migrations.AddField(
            model_name='editor',
            name='permitted_countries',
            field=models.ManyToManyField(blank=True, help_text='Countries the user can work with.', related_name='editors', to='indigo_api.Country'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(help_text='Name of this publication', max_length=512),
        ),
    ]
