# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_api', '0072_import_locality_from_indigo_app'),
        ('indigo_app', '0019_remove_moved_locality_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='permitted_countries',
            field=models.ManyToManyField(help_text=b'Countries the user can work with.', related_name='editors', to='indigo_api.Country', blank=True),
        ),
    ]
