# Generated by Django 2.2.13 on 2020-10-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_app', '0020_editor_permitted_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='permitted_countries',
            field=models.ManyToManyField(blank=True, help_text='Countries the user can work with.', related_name='editors', to='indigo_api.Country'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(help_text='Name of this publication', max_length=512),
        ),
    ]
