# Generated by Django 2.2.14 on 2020-07-08 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name of this resolver', max_length=255, unique=True)),
                ('url', models.URLField(blank=True, help_text='Website for this authority (optional)', null=True)),
                ('not_found_url', models.URLField(blank=True, help_text='URL of a 404 page (optional)', null=True)),
                ('slug', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_.]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores, dots or hyphens.", 'invalid')])),
            ],
            options={
                'verbose_name_plural': 'Authorities',
            },
        ),
        migrations.CreateModel(
            name='AuthorityReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frbr_uri', models.CharField(db_index=True, help_text='FRBR Work or Expression URI to match on', max_length=255)),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('url', models.URLField(help_text='URL from which this document can be retrieved', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='indigo_resolver.Authority')),
            ],
            options={
                'unique_together': {('authority', 'frbr_uri')},
            },
        ),
    ]
