# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 10:59
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_resolver', '0002_auto_20170421_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='url',
            field=models.URLField(blank=True, help_text='Website for this authority (optional)', null=True),
        ),
    ]
