# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_resolver', '0003_auto_20170506_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
