# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 17:55
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify


def populate_slug(apps, schema_editor):
    Authority = apps.get_model("indigo_resolver", "Authority")
    db_alias = schema_editor.connection.alias

    for authority in Authority.objects.using(db_alias).filter(slug=None).all():
        authority.slug = slugify(authority.name)
        authority.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_resolver', '0004_authority_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slug, migrations.RunPython.noop),
    ]
