# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_resolver', '0005_resolver_slug_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='slug',
            field=models.SlugField(),
        ),
    ]
