# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 10:01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_resolver', '0006_require_authority_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='not_found_url',
            field=models.URLField(blank=True, help_text='URL of a 404 page (optional)', null=True),
        ),
    ]
