# Generated by Django 2.2.13 on 2021-04-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_resolver', '0007_authority_not_found_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='priority',
            field=models.IntegerField(default=10, help_text='When multiple resolvers match, highest priority wins'),
        ),
        migrations.AddField(
            model_name='authorityreference',
            name='priority',
            field=models.IntegerField(blank=True, help_text="Priority for this URL. If unset, uses the authority's priority", null=True),
        ),
    ]
