# Generated by Django 3.2.15 on 2024-03-07 15:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('indigo_resolver', '0008_auto_20210409_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authority',
            options={'verbose_name': 'authority', 'verbose_name_plural': 'authorities'},
        ),
        migrations.AlterModelOptions(
            name='authorityreference',
            options={'verbose_name': 'authority reference', 'verbose_name_plural': 'authority references'},
        ),
        migrations.AlterField(
            model_name='authority',
            name='name',
            field=models.CharField(help_text='Descriptive name of this resolver', max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='not_found_url',
            field=models.URLField(blank=True, help_text='URL of a 404 page (optional)', null=True, verbose_name='not found URL'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='priority',
            field=models.IntegerField(default=10, help_text='When multiple resolvers match, highest priority wins', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_.]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores, dots or hyphens.", 'invalid')], verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='url',
            field=models.URLField(blank=True, help_text='Website for this authority (optional)', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='authorityreference',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='indigo_resolver.authority', verbose_name='authority'),
        ),
        migrations.AlterField(
            model_name='authorityreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='authorityreference',
            name='frbr_uri',
            field=models.CharField(db_index=True, help_text='FRBR Work or Expression URI to match on', max_length=255, verbose_name='FRBR URI'),
        ),
        migrations.AlterField(
            model_name='authorityreference',
            name='priority',
            field=models.IntegerField(blank=True, help_text="Priority for this URL. If unset, uses the authority's priority", null=True, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='authorityreference',
            name='title',
            field=models.CharField(help_text='Document title', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='authorityreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='authorityreference',
            name='url',
            field=models.URLField(help_text='URL from which this document can be retrieved', max_length=1024, verbose_name='URL'),
        ),
    ]
